pipeline {
    agent any
    }
    environment {
        DOCKERHUB_CREDENTIALS = credentials('docker-hub-creds')
        DOCKER_REGISTRY = 'nashpaz123'
        REPO_NAME = 'fe-exam'  // Change to 'be-exam' for backend pipeline
        IMAGE_TAG = "${env.BUILD_NUMBER}"
        HELM_REGISTRY = 'oci://your-helm-registry'
    }
    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'workshop/argo-jenkins-exam', url: 'https://github.com/nashpaz123/devopshift-welcome.git'
            }
        }
        
        stage('Lint & Security Scan') {
            steps {
                sh 'pip install flake8 bandit'
                sh 'flake8 . ||true'
                sh 'bandit -r . ||true'
            }
        }
        
        stage('Install Dependencies') {
            steps {
                sh """
                   pwd
                   ls
                   pip install -r exam-code/docker/fe/requirements.txt
                """
            }
        }
        
        stage('Build Docker Image') {
            steps {
                sh """
                   pwd
                   ls
                   cd exam-code/docker/fe/
                   docker build -t $DOCKER_REGISTRY/$REPO_NAME:$IMAGE_TAG .
                   docker tag $DOCKER_REGISTRY/$REPO_NAME:$IMAGE_TAG $DOCKER_REGISTRY/$REPO_NAME:latest
                """
            }
        }
        
        stage('Run Tests in Container') {
            steps {
                sh "docker run --rm $DOCKER_REGISTRY/$REPO_NAME:$IMAGE_TAG pytest tests/"
            }
        }
        
        stage('Integration Test with Docker Compose') {
            steps {
                sh """
                cp -a exam-code/docker/docker-compose.yaml .
                curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && chmod +x /usr/local/bin/docker-compose
                docker-compose -f exam-code/docker/docker-compose.yaml up -d
                """
                sleep time: 20, unit: 'SECONDS'  // Wait for services to start
                sh 'curl -f http://localhost:5002 || exit 1'  // Adjust port for backend if needed
                sh 'docker-compose down'
            }
        }
        
        stage('Push to Docker Hub') {
            steps {
                sh "echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin"
                sh "docker push $DOCKER_REGISTRY/$REPO_NAME:$IMAGE_TAG"
                sh "docker push $DOCKER_REGISTRY/$REPO_NAME:latest"
            }
        }
        
        stage('Update Helm OCI Chart') {
            steps {
                sh 'helm registry login $HELM_REGISTRY --username $DOCKERHUB_CREDENTIALS_USR --password $DOCKERHUB_CREDENTIALS_PSW'
                sh "helm package helm-chart && helm push helm-chart-*.tgz $HELM_REGISTRY"
            }
        }
    }
}